builds:
  -
    goos:
      - darwin
      - linux
      - windows
    ignore:
      - goos: darwin
        goarch: 386
    env:
      - CGO_ENABLED=0
    main: main.go
archives:
  -
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
 skip: true

brew:
  github:
    owner: kubemq-io
    name: homebrew-tap