# github.com/go-task/task

version: '2'

vars:
  BINARY_NAME: kubetools
  VERSION: v1.1.0

tasks:
  default:
    cmds:
      - task: build_win
      - task: build_mac
      - task: build_linux_64
      - task: build_linux_32
  build_win:
    env:
      GOOS: windows
      GOARCH: amd64
    cmds:
      - go build -o "{{.BINARY_NAME}}.exe" -ldflags "-X main.version={{.VERSION}}"
      - go build -o "./bin/windows/{{.BINARY_NAME}}.exe" -ldflags "-X main.version={{.VERSION}}"
  build_mac:
    env:
      GOOS: darwin
      GOARCH: amd64
    cmds:
      - go build -o "./bin/macos/{{.BINARY_NAME}}_darwin_amd64" -ldflags "-X main.version={{.VERSION}}"
 #   - git update-index --chmod=+x "./bin/macos/{{.BINARY_NAME}}_darwin_amd64"
  build_linux_64:
    env:
      GOOS: linux
      GOARCH: amd64
    cmds:
      - go build -o "./bin/linux64/{{.BINARY_NAME}}_linux_amd64" -ldflags "-X main.version={{.VERSION}}"
 #     - git update-index --chmod=+x "./bin/linux64/{{.BINARY_NAME}}_linux_amd64"
  build_linux_32:
    env:
      GOOS: linux
      GOARCH: 386
    cmds:
      - go build -o "./bin/linux32/{{.BINARY_NAME}}_linux_386" -ldflags "-X main.version={{.VERSION}}"
  #    - git update-index --chmod=+x "./bin/linux32/{{.BINARY_NAME}}_linux_386"